### ISSUE TITLE
The importer is not working on ubuntu 18.04

### ISSUE THREAD

**Issue by AlbertCoca** [ibiza240/MTGAHelper-Windows-Client#11]
When I try to run the importer as explained in the webside on ubuntu it give me this error:

```
$ wine MTGAHelper.ConsoleSync.exe 29b6cad44d0d43e1b57c6ea54efd48d8 "C:\Users\albert\AppData\LocalLow\Wizards Of The Coast\MTGA\output_log.txt"
Initializing...
Unhandled exception. System.Net.Http.HttpRequestException: Remote server unavailable
 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MTGAHelper.ConsoleSync.Services.ServerApiCaller.GetResponseSimple[T](String apiEndpoint)
   --- End of inner exception stack trace ---
   at MTGAHelper.ConsoleSync.Services.ServerApiCaller.GetResponseSimple[T](String apiEndpoint)
   at MTGAHelper.ConsoleSync.Services.ServerApiCaller.GetCards()
   at MTGAHelper.ConsoleSync.Program.Main(String[] args)
002c:err:eventlog:ReportEventW L"Application: MTGAHelper.ConsoleSync.exe\nCoreCLR Version: 4.700.19.60701\n.NET Core Version: 3.1.1\nDescription: The process was terminated due to an unhandled exception.\nException Info: System.Net.Http.HttpRequestException: Remote server unavailable\r\n ---> System.AggregateException: One or more e"...
wine: Unhandled exception 0xe0434352 in thread 2c at address 0x7b44c1e7 (thread 002c), starting debugger...

```

**Comment by AlbertCoca** [comment]
Hello, This is still not working.

In your website is said that you have a way to upload the logs in macos and linux. I understand that you might not want to give support to linux users. But maybe you could at least remove the text from the webpage.

![image](https://user-images.githubusercontent.com/20433529/106386181-07340b80-63d4-11eb-8c7d-240cca1ba8b3.png)

**Comment by ibiza240** [comment]
Hi!

The cross-platform console program that can be used to upload a log file can be found here:
https://github.com/ibiza240/MTGAHelper-Windows-Client/blob/master/MTGAHelper.ConsoleSync.exe.zip

It has been updated for the latest expansion (Kaldheim) and can be used to upload your log file.

For example, if I want to run it on Windows, I do it with 2 parameters like this:
> dotnet _a1b2c3xxxMyMtgaHelperUserIdxxxa1b2c3_ "%AppData%\..\LocalLow\Wizards Of The Coast\MTGA\Player.log"

![image](https://user-images.githubusercontent.com/6589646/106388218-86611980-63ab-11eb-8dd8-b7576b630248.png)

**Comment by ibiza240** [comment]
Hi @AlbertCoca !

Here's a message I received from a Ubuntu user that is successfully running the console program, hope this can help you and others!

- Need to install specific dotnet version of 3.1.x I used snap for that ("sudo snap install dotnet-sdk --classic --channel=3.1/stable")

- Need to put the "Player.log" file inside the "MTGAHelper.ConsoleSync.exe" folder, as the argument only works relative to path. So this is the only version that worked for me: dotnet MTGAHelper.ConsoleSync.dll "2d39dd1eb1d246e0a3ed5e60eaba7a9e" "Player.log"

A trick for the last one is to simply make a symlink though, which works. So symlinking "Player.log" inside the "MTGAHelper.ConsoleSync.exe" folder to the actual location of the "Player.log" in the wine location.
