### ISSUE TITLE
Deathsie's Draft Rankings All Show 0 For Some Sets

### ISSUE THREAD

**Issue by softienerd** [ibiza240/MTGAHelper-Windows-Client#12]
Ravnica Allegiance ranked draft is available right now.

When I set MTGAHelper to use deathsie's ranking, all cards show 0 instead of the value from Deathsie's spreadsheet. THB and newer sets seem to work properly.

**Comment by ibiza240** [comment]
Currently these sets support Deathsie ratings:
> DOM, GRN, ELD, THB and IKO

More sets will be added as they respectively get playable for a period of time in MTGA
