### ISSUE TITLE
1.4.2 Not showing collection quantity or draft rankings

### ISSUE THREAD

**Issue by Marthisdil** [ibiza240/MTGAHelper-Windows-Client#15]
When drafting, current version isn't showing collection quantities (for rare drafting), etc, regardless of which draft ranking choice is made.

**Comment by pboutet** [comment]
Having the same issue as above.

**Comment by Figjam81** [comment]
I am experiencing this same issue. Any help?

**Comment by ibiza240** [comment]
HI @Marthisdil and @Figjam81,

the MTGA log file does not contain the card ids anymore when drafting with humans (Traditional or Premier) unfortunately :( That's how WotC implemented them it seems, so all trackers providing limited ratings while picking cards are now disrupted.

However I am working on a new DraftHelper that will work even with this change, for now it's beta and only available to supporters though. You can go check the Patreon if you are interested in trying the early version.

Thanks for reporting!
