### ISSUE TITLE
Error since new update

### ISSUE THREAD

**Issue by Figjam81** [ibiza240/MTGAHelper-Windows-Client#16]
Error at startup: Check the latest application log file for details or contact me on Discord if you need more help.

Could not load file or assembly 'Microsoft.Extensions.Configuration,Verison=2.2.0.0, Culture = neutral, PublicKeyToken=adb9793829DDAE60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by ibiza240** [comment]
Hi! Thanks for your message,

Please redownload the latest .msi package and reinstall fresh and it should fix it.
Sorry for the inconvenience, this is a one-time issue upgrading from the version 1.4.2
