### ISSUE TITLE
Auto-updater not functioning

### ISSUE THREAD

**Issue by alexander-novo** [ibiza240/MTGAHelper-Windows-Client#21]
After thee recent update, opening up the tracker prompts that I must install the update to proceed. When I click 'Yes', an Administrator permission window pops up. When I accept this, a terminal pops up for a split second and disappears. Then nothing else happens. When I re-open the tracker, the same thing happens.

OS: Windows 10

**Comment by ibiza240** [comment]
Hi, thanks for reporting this.

To help diagnose what is wrong, could you do this for me please?

1. Go to the `C:\Users\[username]\AppData\Roaming\MTGAHelper` directory in Windows Explorer
2. Type `cmd` in the address bar and hit Enter (a command prompt will open)
3. Type `MTGAHelper.Tracker.AutoUpdater.exe` in the command prompt and this will start the Auto-updater but will not close the window once it encounters the problem
4. Post a screenshot with the error message in the command prompt

Thanks!

**Comment by alexander-novo** [comment]
```
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\<user>\AppData\Roaming\MTGAHelper\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64```

**Comment by ibiza240** [comment]
Thanks! Now I see what it is.

I pushed an update on the server, can you retry opening the tracker and see if the auto update process works now?

**Comment by alexander-novo** [comment]
Perfect, seems fixed!

**Comment by ibiza240** [comment]
Thanks for letting me know that you had this problem :)
