### ISSUE TITLE
Auto Updater resulting in broken installation

### ISSUE THREAD

**Issue by Birne94** [ibiza240/MTGAHelper-Windows-Client#24]
When starting the application today, I received the update notification and installed the new version. After that, I was unable to launch the application again and received the following error:

```
06 11:02:47 [INF] () C:\Program Files (x86)\MTGAHelper\MTGAHelper Tracker
06 11:02:47 [ERR] () Error at startup:
System.MissingMethodException: Methode nicht gefunden: "SimpleInjector.Container MTGAHelper.Lib.IoC.SimpleInjectorRegistrations.RegisterFileLoadersShared(SimpleInjector.Container)".
   bei MTGAHelper.Lib.OutputLogParser.IoC.SimpleInjectorRegistrations.RegisterFileLoaders(Container container)
   bei MTGAHelper.Tracker.WPF.App.CreateContainer(ConfigModel configModelApp, String folderData)
   bei MTGAHelper.Tracker.WPF.App.ConfigureApp()
   bei MTGAHelper.Tracker.WPF.App.<StartApp>d__9.MoveNext()
```

(_Methode nicht gefunden_ means _Method not found_ in the exception's English version, not sure why the runtime is even translating this.)

Uninstalling and then installing the application fixed the problem for me, but I think there might be something wrong with the update process.

---

Unrelated to this, I also found some Internal Server Errors in the logs, just to let you know:

```
05 20:56:54 [ERR] () Managed error in WrapNetworkStatus:
System.Net.Http.HttpRequestException: Der Antwortstatuscode gibt keinen Erfolg an: 500 (Internal Server Error).
   bei System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   bei MTGAHelper.Tracker.WPF.Business.ServerApiCaller.PostResponseSimple[TReturn](String apiEndpoint, Object body, Boolean isPut)
   bei MTGAHelper.Tracker.WPF.Business.ServerApiCaller.UploadOutputLogResult2(String userId, OutputLogResult2 result2)
   bei MTGAHelper.Tracker.WPF.Views.MainWindow.<>c__DisplayClass34_1.<UploadInfoToServer>b__1()
   bei MTGAHelper.Tracker.WPF.ViewModels.MainWindowVM.WrapNetworkStatus(NetworkStatusEnum status, Action workToDo)

```

**Comment by maturz** [comment]
Had same issue and something like it on the update before this one, "repair" did not solve it, had to uninstall. This time however there is no uninstall to use but you can uninstall by downloading the msi file and running that (after reinstall the uninstall option is back).
