### ISSUE TITLE
Collection Disparity

### ISSUE THREAD

**Issue by runkatrun** [ibiza240/MTGAHelper-Windows-Client#26]
I noticed that my collection as it shows in MTGAHelper is off somewhat after comparing it to the excel sheet I keep for my own records. 

Just for a specific example, I own all four copies of Fortress Crab in M20, but MTGAHelper shows me as missing all four copies.

Not sure if this would be a log issue itself, as the copies do show up in Arena, or if this is an actual issue with the program, so just figured I'd drop this here just to cover all bases. Thanks for everything.

**Comment by omarjuul** [comment]
Thanks for reporting this! Some cards (Fortress Crab and 2 more) were wrongly recorded twice in the collection info. This has been fixed.

It should be good now, but if you have some other cards that are off please let us know!
