### ISSUE TITLE
Window position does not respect toolbar placement

### ISSUE THREAD

**Issue by ulirg** [ibiza240/MTGAHelper-Windows-Client#3]
The tracker windows always opens against the left edge of the screen, even when the Windows toolbar is set to be on the left side. So the tracker window partially covers the toolbar at startup.

Tracker window's initial position should be offset as to not obscure the toolbar, or it should remember its last size and position and reposition the same way at the next startup.

**Comment by ibiza240** [comment]
Thanks for the feedback!

In the next version (released in a few days) the tracker will remember its size and position.

I will close this issue when the new version is out.

Let me know if your problem is not fixed with this solution :)
