### ISSUE TITLE
Sync does not update web interface

### ISSUE THREAD

**Issue by Gander7** [ibiza240/MTGAHelper-Windows-Client#34]
![image](https://user-images.githubusercontent.com/4229134/129428345-53fdcf52-ec73-4759-b752-e7ea087db5b5.png)

Did this a few times over 5 hours ago and https://mtgahelper.com/ has not updated for my stats.
I've played alot on my mobile phone, and then 3-5 games today on the computer. I closed mtga and then ran the sync(Detailed Stats are on).

I expected my stats to be updated on the web interface, possibly with a few minutes lag (max 5ish hopefully).
This sync has worked before, I haven't run it in about 2 weeks tho.
Is there anyway I can print out verbose logs or a version from the tool that would give you more information?

**Comment by Gander7** [comment]
I was able to bring in my collection changes by remove the numbers from the user id so it matched the user id in my profile.
My matches, that I played on the computer with the log didn't get imported. The tool says "0 matches" found even though I played 4-5 earlier today.

**Comment by Gander7** [comment]
It's back to not working, no changes to code. I played a few games and went to sync.
![image](https://user-images.githubusercontent.com/4229134/130729635-4eb908fc-06f5-49ad-b3ed-3058d41ded5c.png)

**Comment by cctvfm** [comment]
I'm having the same issue, I also have a username with 'hidden numbers' like Gander7.

**Comment by Gander7** [comment]
Seems like, based on the PatchNotes.md file (updated 10 days ago), the collection is broken right now.

**Comment by Kryptortio** [comment]
> Seems like, based on the PatchNotes.md file (updated 10 days ago), the collection is broken right now.

From MTGA pro (open source, so an example for how it can be solved):

> [With Tracker v.2.2.3 collection and inventory tracking should be relatively stable.](https://github.com/Razviar/mtgap/issues/266#issuecomment-929957571)

**Comment by ibiza240** [comment]
Hello, as you might be aware, WotC broke all the trackers a few weeks ago.

The MTGAHelper v1,8,1 update should restore tracking for Windows users, please check [this short guide](https://github.com/ibiza240/MTGAHelper-Windows-Client/blob/master/Manual-upload-1-8-1.md) if you are manually uploading your log file.
