### ISSUE TITLE
Tracker not working after  8/24 update

### ISSUE THREAD

**Issue by icterine** [ibiza240/MTGAHelper-Windows-Client#35]
Tracker not working after  8/24 update 

as I know it is common issue for almost all 3rd party tool as WoTC cut logging on official client.

However, seems on client via Epic game launcher, most logging still present and maybe workaround to fix tracker.

**Comment by ibiza240** [comment]
Hello! Many things were changed by WotC in the log file so that broke all the trackers.

I've released a first patch restoring a couple of features, more to come.
