### ISSUE TITLE
The latest version of the Tracker does not install

### ISSUE THREAD

**Issue by MAC-GH** [ibiza240/MTGAHelper-Windows-Client#41]
Hello,

Once the installer prompts to download the .Net Core 6.0 and whatever I click Yes or No to download (btw, why does it not detect that the required runtime is already installed ?) the process stops whether it opens the .Net download page or not => there is no running process allowing to pursue the installation. If I run the installer again this scenario repeats.

Any ideas what could be wrong, please ?

Kind regards

Edit: sorry to bother - the problem was that I had the .Net runtime installed and not the **desktop** .Net runtime => this issue can be closed

**Comment by ibiza240** [comment]
Hi Mac,
thanks for your message.

I made an update, can you try the following:

1. Uninstall completely any local version of MTGAHelper
2. Install the .NET 6 runtime here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.0-windows-x64-installer
3. Download a fresh copy of the installer here: https://www.mtgahelper.com/download/MTGAHelperTracker.msi
4. Install the latest version and it should work

**Comment by MAC-GH** [comment]
The problem was that I had the .Net runtime installed and not the desktop .Net runtime. Once the desktop .Net runtime was installed everything went smoothly.
