### ISSUE TITLE
Rare lands in tracked decks

### ISSUE THREAD

**Issue by Arkewas** [ibiza240/MTGAHelper-Windows-Client#47]
Hello,
when I check for tracked decks in Advisors > Decks to play menu I notice that rare lands doesn't count towards "Missing cards weight". Instead I think they should count to reflect the true weight of a deck.

Best regards

**Comment by ibiza240** [comment]
Hi, thanks for the feedback. Can you provide some screenshots please to better troubleshoot the problem?

**Comment by Arkewas** [comment]
Hello,
here it is: as you can see from this screenshot

![Rare lands](https://user-images.githubusercontent.com/85570370/174974294-34538bfb-9ee9-49a7-b0c1-a7139398de50.jpg)

the deck "Rakdos Lurrus", for example,  has a weight of 60 points only, even if there are 9 rare lands in it.

The rarity weight's points should be as these:

Common (30 points)     Uncommon (40 points)     Rare (120 points)	    Mythic (150 points)

Also I noticed just a few minutes ago that the weight points fo Common and Uncommon cards are swapped as you can see from this screenshot (a Uncommon card values more then a Common one of course)

![Common, Uncommon](https://user-images.githubusercontent.com/85570370/174975727-fe2452dc-7f17-4bb2-b9a4-9a43bc78ac94.jpg)

Thank you

**Comment by Arkewas** [comment]
Thank you for your help. I didn't know cards' rarity weight could be assigned in Profile page.
I set cards' rarity  weight both in deck and sideboard like the values i specified in my previous post and after updating the values the issue was solved.

Best regards

**Comment by ibiza240** [comment]
Great! Happy to help
