### ISSUE TITLE
New 1.2.5 client issues

### ISSUE THREAD

**Issue by EdHuangGit** [ibiza240/MTGAHelper-Windows-Client#6]
Followed automatic uninstall and install of new 1.2.5 client

After Google Oauth sign-in , using the MTGAHelper Link from the Client, the Webpage doesn't load (blank gray screen)

When using another browser to sign-in with Google, data loads, but lost all the previous history data.

**Comment by ibiza240** [comment]
Hi, do you know is your user ID? I can help you making it work, we can
continue this on Discord or email?

**Comment by EdHuangGit** [comment]
Sure how do I find you on Discord?

**Comment by ibiza240** [comment]
Here is the link to join: https://discord.gg/GTd3RMd

**Comment by ibiza240** [comment]
Oh and reading again your first post, I think you simply have to do Ctrl-F5, to refresh the website and javascript. You can try that and let me know :)
