### ISSUE TITLE
MTGAHelper can't find any compatible framework version w/ .NET Core 3.1.1 installed

### ISSUE THREAD

**Issue by jtoohill** [ibiza240/MTGAHelper-Windows-Client#9]
When I try to run MTGAHelper, nothing happens. I installed .NET Core Runtime  - 3.1.1 (x64) from here:  https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.1-windows-x64-installer

It shows up as being installed in my programs list, version 3.1.1.28408.

I did not try to install the version linked from your README.md, since it is older than the most recent security patch. (You might consider using https://dotnet.microsoft.com/download/dotnet-core/current/runtime as a stable link to the most recent version.)

When I try to invoke it from the cmdline:

```
C:\>dotnet "C:\Program Files (x86)\MTGAHelper\MTGAHelper Tracker\MTGAHelper.Tracker.dll"
It was not possible to find any compatible framework version
The framework 'Microsoft.WindowsDesktop.App', version '3.0.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.WindowsDesktop.App&framework_version=3.0.0&arch=x64&rid=win10-x64
```

That link ends up taking me to the same place where I installed the .NET Core Runtime.

e: There are also no logs in `%appdata%\MTGAHelper`.

**Comment by ibiza240** [comment]
Thanks for your detailed feedback and link recommendation, I will do that.

I am not sure what is happening here, it should be working with the latest .Net Core version, and I am pretty sure from your description that you installed it correctly.

I will do some testing and get back to you

**Comment by ibiza240** [comment]
Ok so I did some tests, here's what I found out:

I first installed .NET Core Runtime 3.1.1
Tried to run MTGAHelper and got the same message as you:
> It was not possible to find any compatible framework version
> The framework 'Microsoft.WindowsDesktop.App', version '3.0.0' was not found.
>   - No frameworks were found.

I then uninstalled the .NET Core Runtime 3.1.1
and installed the Desktop Runtime 3.1.1
Tried to launch the program and it works

So my question:
Are you sure you really installed the Desktop Runtime?
I first installed the .NET Core Runtime only at first by mistake, so maybe that is the same for you?

Thanks!

**Comment by ibiza240** [comment]
Let me know if that was it for you :)
I'll eventually close it, without an update

**Comment by jtoohill** [comment]
Installing .NET Core *Desktop* Runtime 3.1.1 resolved the issue. I must've installed the .NET Core (non-Desktop) Runtime, which the readme was previously vague about. I see you've since updated the install process to not require separate installation, thanks for addressing that!

**Comment by johnfercher** [comment]
I think this issue keep going, I can't run MTGAHelper
